### ISSUE TITLE
beginner/nlp/deep_learning_tutorial.py 번역 개선

### ISSUE THREAD

**Issue by creduo** [PyTorchKorea/tutorials-kr#163]
## 문서 URL
- **URL**: https://tutorials.pytorch.kr/beginner/nlp/deep_learning_tutorial.html

## 변경 사항
전체적으로 재번역

## 추가 정보
별다른 추가 정보는 없습니다. 글을 다듬을 예정입니다.

**Comment by 9bow** [comment]
진행되지 않은지 오래되어 이슈를 닫습니다.
제가 잘못 닫거나, 진행 중이신 경우 이슈를 다시 열어주시고 덧글로 알려주세요.
