### ISSUE TITLE
용어집 개선 제안 (gradient)

### ISSUE THREAD

**Issue by eric-yoo** [PyTorchKorea/tutorials-kr#243]
## 이슈 내용
_어떤 이슈인지 알려주세요._
용어집에서 gradient (변화도)라는 단어는 편미분 값이라는 의미를 잘 드러내지 못하기 때문에 "기울기"로 수정을 제안합니다.
혹은 gradient explosion 등의 파생어를 고려하여 음차표기 (그래디언트) 하는 것도 방안이 될 것 같습니다.

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
