### ISSUE TITLE
번역 규칙 추가 제안 (augmentation)

### ISSUE THREAD

**Issue by zzaebok** [PyTorchKorea/tutorials-kr#248]
## 문서 URL
https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md

## 변경 사항
augmentation 에 대한 번역규칙이 추가되면 좋을 것 같습니다.

## 추가 정보
Data augmentation은 자주 사용되는 용어로 부족한 데이터셋을 늘리기 위해/데이터 불균형을 해소하기 위해 기존 데이터셋에 변화를 가해 이를 풍부하게 하는 방법을 의미합니다.
흔히 "데이터 증강"라는 단어로 번역되곤 하지만 일부 "데이터 증가"라고 번역하는 글들도 있습니다.
해당 레포에서도 "증강"(`intermediate_source/torchvision_tutorial.rst`) 과 "증가" (`beginner_source/transfer_learning_tutorial.py`)가 혼용되어 사용되고 있습니다.
하지만 단순히 데이터를 양적으로만 증가시키는 것이 아닌, 여러 작업 (jitter, rotate, etc..) 을 통해 데이터셋을 부풀리는 작업이니만큼 "증강"이라는 단어로 번역 규칙을 만드는 것이 좋아보입니다.

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
