### ISSUE TITLE
Task 번역 제안

### ISSUE THREAD

**Issue by puhuk** [PyTorchKorea/tutorials-kr#249]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**:

1. https://tutorials.pytorch.kr/beginner/translation_transformer.html (원문: https://pytorch.org/tutorials/beginner/translation_transformer.html)

2. https://tutorials.pytorch.kr/intermediate/reinforcement_q_learning.html (원문: https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html)

3. https://tutorials.pytorch.kr/intermediate/dynamic_quantization_bert_tutorial.html (원문: https://pytorch.org/tutorials/intermediate/dynamic_quantization_bert_tutorial.html)

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_
Task 에 대한 번역이 통일되면 좋겠습니다.
위 URL 에서 마지막 URL의 경우에는 "분야(문제)" 로의 기존 번역이 매끄러워 변경하지 않아도 괜찮을 것 같습니다.

하지만 첫번째의 경우 "작업(task)" 으로 번역, 두번째 URL의 경우 "태스크"로 음차표기되어 있어, 이후 번역을 위해서도 task 번역에 통일성을 갖는 것이 좋을 것 같습니다.

위 3번의 케이스처럼 분야 또는 문제로 번역하여 자연스러운 경우, 해당 단어를 사용하고, 그렇지 않은 경우 "태스크" 로 번역하는 것을 제안합니다.

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
