### ISSUE TITLE
번역 용어집 단어 추가 - Finetuning

### ISSUE THREAD

**Issue by miNept** [PyTorchKorea/tutorials-kr#256]
## 이슈 내용
_어떤 이슈인지 알려주세요._
Finetuning을 "미세조정"으로 번역을 제안합니다.
"미세학습"도 좋은 번역으로 생각을 하고있는데, 보통 finetuning은 pretrained된 모델을 
원하는 데이터에 맞추는 과정에서 사용되는 것을 고려해, "미세조정"으로 번역했습니다.

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
