### ISSUE TITLE
용어집 추가 제안(feature)

### ISSUE THREAD

**Issue by spongebob03** [PyTorchKorea/tutorials-kr#264]
## 이슈 내용
_어떤 이슈인지 알려주세요._
많이 쓰이는 단어인 `feature` 에 대한 번역규칙 추가를 제안합니다. 

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._

feature를 음차표기한 `피쳐`, `피처`도 많이 쓰이지만 `특징`으로 사용한다면 이후 feature selection을 `특징 선택`, feature extraction을 `특징 추출`로 자연스럽게 번역할 수 있다는 점을 고려하였습니다. 
머신러닝에서 항상 다루는 feature를 어떻게 표현하면 좋을지 토의하고 정의하고 싶습니다.

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
