### ISSUE TITLE
번역 용어집 단어 추가 - Training

### ISSUE THREAD

**Issue by hrxorxm** [PyTorchKorea/tutorials-kr#268]
## 이슈 내용

"Training"을 "학습" 또는 "훈련"이라고 번역할 수 있는데,
튜토리얼 전반적으로 "학습"이라고 번역하고 있는 것 같습니다.
간혹 "훈련"이라고 번역된 것을 발견하긴 했는데, 용어집에 "학습"이라고 번역할 것을 명시하여 일관성 있는 번역을 할 수 있으면 좋을 것 같습니다.

## 추가 정보

- URL: https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
