### ISSUE TITLE
번역 용어집 단어 추가 - Data Loader

### ISSUE THREAD

**Issue by jha929** [PyTorchKorea/tutorials-kr#277]
## 문서 URL
- **URL**: https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md

## 변경 사항
* 번역 가이드 용어집에 "bias" 를 "편향"으로 번역하는 규칙을 추가하고자 합니다.

## 추가 정보
* `Dataset`이 용어집에 정의되어 있는 만큼, `Data Loader`도 추가하면 좋을 것 같습니다.

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
