### ISSUE TITLE
TRANSLATION_GUIDE의 단어목록 추가 - forward propagation

### ISSUE THREAD

**Issue by Jo-ad-fontes** [PyTorchKorea/tutorials-kr#279]
## 이슈 내용
_어떤 이슈인지 알려주세요._
용어집에 추가할 단어로 forward propagation | 순전파를 제안합니다.

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._
forward propagation의 번역으로 순전파라는 단어는 여러 곳에서 굳혀진 것 같습니다.

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
