### ISSUE TITLE
번역 용어집 단어 제안 - fork

### ISSUE THREAD

**Issue by YonghyunRyu** [PyTorchKorea/tutorials-kr#287]
## 이슈 내용
번역 용어 제안
fork 를 복제로 번역해야 할 것 같습니다.

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._
https://tutorials.pytorch.kr/intermediate/dist_tuto.html 에서 생성(fork)로 번역하였습니다.

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
