### ISSUE TITLE
Fully-connected layer에 대한 번역어 제안

### ISSUE THREAD

**Issue by jafffy** [PyTorchKorea/tutorials-kr#292]
## 이슈 내용
_어떤 이슈인지 알려주세요._

Fully-connected layer에 대한 번역어로서 Fully-connected 계층을 제안합니다.

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
