### ISSUE TITLE
Transform 및 Transformation 에 대한 번역어 제안

### ISSUE THREAD

**Issue by jafffy** [PyTorchKorea/tutorials-kr#294]
## 이슈 내용
_어떤 이슈인지 알려주세요._

Transform 및 Transformation에 대해 현재 번역의 "변형"을 대신하는 "변환" 이라는 번역어를 사용할 것을 제안합니다. 

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
