### ISSUE TITLE
번역 용어집 단어 추가 - label

### ISSUE THREAD

**Issue by joonkeekim** [PyTorchKorea/tutorials-kr#297]
## 이슈 내용
_어떤 이슈인지 알려주세요._
"label"이 정답이나 라벨, 레이블 등으로 번역이 되어있는데
더 널리 쓰이는 번역인 라벨로 통일하는것이 좋다고 생각하여
라벨로 통일할 것을 제안합니다.

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._
- URL: https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
