### ISSUE TITLE
beginner/audio_preprocessing_tutorial.py 목차 하이라이팅 오류

### ISSUE THREAD

**Issue by hrxorxm** [PyTorchKorea/tutorials-kr#312]
## 이슈 내용

* 목차 하이라이팅 오류

## 추가 정보

* URL : https://tutorials.pytorch.kr/beginner/audio_preprocessing_tutorial.html

* 캡처 후 설명
![오디오목차오류](https://user-images.githubusercontent.com/35680202/132113806-d3c02719-e097-46cc-be76-4fe0444be1ff.png)

  * 목차에서 `Audio manipulation With torchaudio` 부터 `Datasets` 까지 `beginner/audio_preprocessing_tutorial.py` 문서 내용 안의 목차가 반영됩니다.
  * 만약에 오디오 섹션에서 `Audio manipulation With torchaudio` 를 눌러서 이 페이지에 들어가면, 그림과 같이 `Data Augmentation` 목차를 누르면, 페이지 내 이동은 하지만, 왼쪽 목차 하이라이팅이 바뀌지 않습니다.
  * 이 현상이 사진에서 녹색으로 표시한 부분 안에서 똑같이 나타납니다.
  * 목차 하이라이팅이 바뀌지 않아서 혼란이 있을 수 있을 것 같습니다.

* 원본 페이지 문제
  * 원본 페이지에서도 똑같은 현상이 있습니다.
  * URL : https://pytorch.org/tutorials/beginner/audio_preprocessing_tutorial.html

* 어떤 부분이 문제이고, 어떻게 해결할지는 아직 찾지 못했지만, 이슈를 올려보겠습니다.

**Comment by 9bow** [comment]
이슈 감사합니다, @hrxorxm 님.
사실 공식 튜토리얼에도 동일하게 되어 있다보니, 그간 해당 튜토리얼의 내용이 월등하게 길어서 목차를 일부러 빼둔 것이라고 생각했는데 아닐 수도 있겠다는 생각이 들었습니다. ^^;

일단 원인은 [문서 제목에 사용하는 밑줄](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/beginner_source/audio_preprocessing_tutorial.py#L3)과 [동일한 기호](https://github.com/9bow/PyTorch-tutorials-kr/blob/master/beginner_source/audio_preprocessing_tutorial.py#L398)들을 사용해서 그렇습니다.
(Sphinx에서는 밑줄이 등장하는 순서와 중복 여부를 기준으로 목차의 깊이를 나누고 있습니다.)

[해당 튜토리얼을 만든](https://github.com/pytorch/tutorials/commit/c0ffd4e60b98b14f2069e9fef313171286337314) @vincentqb 에게 직접 물어보거나, [공식 튜토리얼에 이슈](https://github.com/pytorch/tutorials/issues)를 올려서 확인해보시면 어떨까요? :)

**Comment by 9bow** [comment]
1.10 버전에서 해당 튜토리얼이 나눠지며 해결되어 이슈를 닫습니다.
제가 잘못 닫거나, 추가하실 내용이 있으시면 이슈를 다시 열어주시고 덧글로 알려주세요.
