### ISSUE TITLE
번역 용어집 단어 추가 - state-of-the-art

### ISSUE THREAD

**Issue by eric-yoo** [PyTorchKorea/tutorials-kr#335]
## 이슈 내용
state-of-the-art 에 대한 의견이 분분한 것 같습니다. 구글 / 파파고 번역기는 "최첨단"이라고 번역을 하지만, 맥락에 따라 유연하게 번역할 필요성이 있는 것 같습니다. 신경망 모델(ex, state-of-the-art ResNet)의 경우 최첨단 (state-of-the-art), 혹은 최첨단이라는 말이 어울리지 않는 맥락(ex, state-of-the-art result)의 경우 최고 수준의 (state-of-the-art) 등으로 번역하는 것이 어떨지 여러분의 의견을 여쭙습니다.

## 추가 정보
- URL: https://github.com/9bow/PyTorch-tutorials-kr/blob/master/TRANSLATION_GUIDE.md

**Comment by Taeyoung96** [comment]
정리가 필요한 용어인 듯 합니다.  
저도 '최고 수준의'가 좀 더 적절한 번역으로 보입니다.

**Comment by 9bow** [comment]
개별 용어집 개선에 대한 이 이슈를 닫고, 용어집의 개선과 관련한 내용은 #426 이슈에서 통합하여 관리하도록 하겠습니다.
