### ISSUE TITLE
saving_and_loading_a_general_checkpoint.py 수정

### ISSUE THREAD

**Issue by spongebob03** [PyTorchKorea/tutorials-kr#338]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**: https://tutorials.pytorch.kr/recipes/recipes/saving_and_loading_a_general_checkpoint.html

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_
1. _``torch.optim`_ 부분 문법 오류 수정
2. 신경망을 구성하고 초기화하기 부분 _더 자세한 내용은 신경망 구성하기 레시피를 참고해주세요._ 의 [사용자가 참고할 레시피 문서](https://tutorials.pytorch.kr/recipes/recipes/defining_a_neural_network.html)를 바로 확인할 수 있도록 링크 추가

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

**Comment by 9bow** [comment]
PR 부탁드립니다~
