### ISSUE TITLE
코드 주석 번역

### ISSUE THREAD

**Issue by jessemin** [PyTorchKorea/tutorials-kr#35]
## 이슈 내용
코드 주석의 경우 번역이 되지 않은 것 같은데, 앞으로 번역되는 튜토리얼부터 함께 번역하는 것이 어떨까요? 예를 들어 https://tutorials.pytorch.kr/advanced/cpp_export.html#converting-to-torch-script-via-tracing의 경우처럼 주석("# An example input you would normally provide to your model's forward() method.")이 길 경우 코드예제를 이해하는데 조금이나마 도움이 될 수 있을 것 같다는 생각이 듭니다.

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._

**Comment by 9bow** [comment]
네, 초기에는 주석도 함께 번역을 한다고 했는데... 지금 다시 살펴보니 빠진 것들이 눈에 띄네요.
기존에 빠뜨렸던 것들도 틈틈이 추가하도록 하겠습니다. :)

**Comment by 9bow** [comment]
현재 번역 중인 문서들은 주석도 함께 번역되고 있어 이 이슈를 닫습니다.
제가 잘못 닫거나, 추가하실 내용이 있으시면 이슈를 다시 열어주시고 덧글로 알려주세요.
