### ISSUE TITLE
beginner/audio_feature_augmentation_tutorial.py 번역 예정

### ISSUE THREAD

**Issue by kimgooq** [PyTorchKorea/tutorials-kr#392]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_
- **URL**:https://tutorials.pytorch.kr/beginner/audio_feature_augmentation_tutorial.html

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
_(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)_
* 예상 완료 일정: 2일

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 변경하지 않으셔도 됩니다.)_
* 관련 이슈: #387 (v1.10)

**Comment by 9bow** [comment]
단순 번역기를 통한 번역 PR로 보여서 전체 PR들을 닫습니다. (#406 및 #409 등)
적절하게 번역이 되었는지 확인을 하는 작업은 번역과 비슷하거나 더 많은 시간과 노력을 필요로 하는 작업이므로,
다른 기여자분들의 시간과 노력을 존중해주시기를 부탁드립니다.
