### ISSUE TITLE
beginner/audio 시리즈 번역

### ISSUE THREAD

**Issue by hrxorxm** [PyTorchKorea/tutorials-kr#436]
## 문서 URL

- **URL** : https://tutorials.pytorch.kr/beginner/audio_io_tutorial.html 를 포함한 `Audio` 시리즈 번역 예정

## (대략적인) 예상 완료 일정

* 예상 완료 일정: 3~4월 중

## 관련 이슈

* 관련 이슈: #387 (v1.10)

**Comment by 9bow** [comment]
안녕하세요, @hrxorxm 님.
이번 v1.11에서 beginner/audio_feature_extraction_tutorial 문서에 일부 변경이 있었습니다.
v1.11 반영 커밋(https://github.com/PyTorchKorea/tutorials-kr/commit/98104878142c962d3a97ca67b5a523c532b41e55)을 참고해주시기를 부탁드립니다. :)

**Comment by 9bow** [comment]
안녕하세요, @hrxorxm 님.
이번 v1.12에서 beginner/audio_* 문서에 많은 변경이 있었습니다. T_T
v1.12 반영 커밋( https://github.com/PyTorchKorea/tutorials-kr/commit/9c9364ebf6797a208a0ac376968630067286a57b )을 참고해주시기를 부탁드립니다. :)

**Comment by bub3690** [comment]
더 진행이 안되는 것으로 보이는데 제가 번역해도 될까요?

**Comment by 9bow** [comment]
네, 기존에 진행하시던 @hrxorxm 님께서 바쁘셔서 당분간 진행이 어려울 것 같습니다. 이 이슈를 닫도록 하겠습니다. 올려주신 #566 처럼 진행해주시면 될 것 같습니다. :)
