### ISSUE TITLE
intermediate/dist_tuto 문서의 오타 수정

### ISSUE THREAD

**Issue by jenner9212** [PyTorchKorea/tutorials-kr#459]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**: https://tutorials.pytorch.kr/intermediate/dist_tuto.html

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_
떄는 때의 오타입니다.
수정해야 합니다.

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

**Comment by 9bow** [comment]
PR이 반영되어 이슈를 닫습니다. :)
