### ISSUE TITLE
 beginner/former_torchies/tensor_tutorial_old 문서의 오타 수정

### ISSUE THREAD

**Issue by mhseo10** [PyTorchKorea/tutorials-kr#464]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**: https://tutorials.pytorch.kr/beginner/former_torchies/tensor_tutorial_old.html

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_
떄 를 때로 바꾸어야 한다고 생각합니다.

![image](https://user-images.githubusercontent.com/81278212/169650826-7c08ff87-4b7e-42fa-ae40-6f71ad2d7f16.png)

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

**Comment by 9bow** [comment]
PR이 반영되어 이슈를 닫습니다. :)
