### ISSUE TITLE
beginner/dcgan_faces_tutorial.html 문서의 오타 수정

### ISSUE THREAD

**Issue by yetniek** [PyTorchKorea/tutorials-kr#466]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**: https://tutorials.pytorch.kr/beginner/dcgan_faces_tutorial.html

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_

'진짜이미지들의' 문장에서 띄어쓰기 오류가 있어 
'진짜 이미지들의'로 문장을 수정하였습니다.  

![image](https://user-images.githubusercontent.com/51157811/169650893-72275d3e-f009-4b1c-92c8-46f7c6ddf0a0.png)

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

**Comment by 9bow** [comment]
PR이 반영되어 이슈를 닫습니다. :)
