### ISSUE TITLE
beginner_source/examples_autograd/polynomial_autograd.py 문서의 오타 수정

### ISSUE THREAD

**Issue by Tieck-IT** [PyTorchKorea/tutorials-kr#476]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**: https://tutorials.pytorch.kr/beginner/examples_autograd/polynomial_autograd.html#sphx-glr-beginner-examples-autograd-polynomial-autograd-py

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_
싼은 산의 오타입니다. 수정해야합니다.

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._
<img width="156" alt="cap" src="https://user-images.githubusercontent.com/90205987/171814844-cd3ed971-0aa7-4ba4-a446-4271de27a710.png">

**Comment by 9bow** [comment]
이슈 감사합니다! PR 진행 부탁드려도 괜찮으실까요?

**Comment by Taeyoung96** [comment]
Merge가 진행된 issue이므로 닫도록 하겠습니다!  😃
