### ISSUE TITLE
TRANSLATION_GUIDE.md (add word)

### ISSUE THREAD

**Issue by kimtaehyeong** [PyTorchKorea/tutorials-kr#522]
## 이슈 내용
TRANSLATION_GUIDE.md 단어 업데이트 하였습니다.

## 추가 정보
|Dropout|드롭아웃|김태형||

**Comment by hyoyoung** [comment]
용어집 pr은 별도의 pr 2개로 나눠주시길 부탁드립니다

**Comment by kimtaehyeong** [comment]
네, 수정하였습니다.
