### ISSUE TITLE
beginner_source/basics/intro.py 연결 링크 오류

### ISSUE THREAD

**Issue by YunjinJo** [PyTorchKorea/tutorials-kr#532]
## 문서 URL
- **URL**: https://tutorials.pytorch.kr/beginner/basics/intro.html

## 변경 사항
<img width="752" alt="스크린샷 2022-08-05 오후 9 13 45" src="https://user-images.githubusercontent.com/42915126/183075534-50024ca5-be62-407a-92cc-6a475b9776db.png">
위 사진 속 "1. 텐서(Tensor)" 링크를 클릭하면 error 404가 뜹니다.

해당 문서의 이름이 변경되면서 업데이트 되지 않은 것 같네요.

## 추가 정보
<img width="650" alt="스크린샷 2022-08-05 오후 9 14 03" src="https://user-images.githubusercontent.com/42915126/183075547-145127a5-394c-419c-9fbc-ccc03b112a66.png">

**Comment by 9bow** [comment]
앗, 그러네요. qs가 빠졌네요ㅠ
