### ISSUE TITLE
용어집 단어 "Inference" 추가

### ISSUE THREAD

**Issue by YunjinJo** [PyTorchKorea/tutorials-kr#561]
## 이슈 내용
기존 번역 내용을 보니 inference를 "추론" 이라고 번역해 둔 문서와 "추론(inference)" 라고 쓰인 문서로 나뉘어 있던데 모두 "추론"으로 통일하는 것이 좋다고 생각합니다.

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._

**Comment by 9bow** [comment]
`추론`이라는 단어가 처음 문서를 읽으시는 분들께는 (혹은 한글 문서를 많이 접하지 않으신 분들께는) 다소 어색하거나 이해하시기 어려운 부분이 있어 문서 초반에 몇 차례 정도는 `추론(inference)`으로 표기를 하고 있습니다.
이는 딱히 추론에만 해당하는 것은 아니고, [일반적인 번역 규칙](https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md#%EC%9D%BC%EB%B0%98-%EA%B7%9C%EC%B9%99)에 따른 것입니다.

> 번역된 문장만으로 의미를 전달하기 어려울 때에는 한글(영어)와 같이 작성합니다.
> 
> * 제목과 본문에 각각 사용되는 경우 첫번째로 해당 용어가 출현하였을 때 매번 함께 작성합니다.
>   * 예. including transposing, indexing, ... => 전치(transposing), 인덱싱(indexing), ...
> * 가급적 한 번씩만 함께 작성하는 것을 원칙으로 하지만 번역자가 임의로 여러번 함께 작성할 수 있습니다.
>   * 예. 직렬화(Serialize)

개인적으로는 기본 문서들에 주로 언급하신 것과 같이 `추론(inference)`로 언급하였었는데요, 혹시 불필요하게 언급된 곳이 있다면 따로 알려주시기를 부탁드립니다.

**Comment by YunjinJo** [comment]
> `추론`이라는 단어가 처음 문서를 읽으시는 분들께는 (혹은 한글 문서를 많이 접하지 않으신 분들께는) 다소 어색하거나 이해하시기 어려운 부분이 있어 문서 초반에 몇 차례 정도는 `추론(inference)`으로 표기를 하고 있습니다. 이는 딱히 추론에만 해당하는 것은 아니고, [일반적인 번역 규칙](https://github.com/PyTorchKorea/tutorials-kr/blob/master/TRANSLATION_GUIDE.md#%EC%9D%BC%EB%B0%98-%EA%B7%9C%EC%B9%99)에 따른 것입니다.
> 
> > 번역된 문장만으로 의미를 전달하기 어려울 때에는 한글(영어)와 같이 작성합니다.
> > 
> > * 제목과 본문에 각각 사용되는 경우 첫번째로 해당 용어가 출현하였을 때 매번 함께 작성합니다.
> >   
> >   * 예. including transposing, indexing, ... => 전치(transposing), 인덱싱(indexing), ...
> > * 가급적 한 번씩만 함께 작성하는 것을 원칙으로 하지만 번역자가 임의로 여러번 함께 작성할 수 있습니다.
> >   
> >   * 예. 직렬화(Serialize)
> 
> 개인적으로는 기본 문서들에 주로 언급하신 것과 같이 `추론(inference)`로 언급하였었는데요, 혹시 불필요하게 언급된 곳이 있다면 따로 알려주시기를 부탁드립니다.

해당 내용 이해 했습니다.
