### ISSUE TITLE
beginner_source/introyt.rst 번역

### ISSUE THREAD

**Issue by kimtaehyeong** [PyTorchKorea/tutorials-kr#567]
## 문서 URL
_번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)_
- **URL**: https://tutorials.pytorch.kr/beginner/introyt.html

## (대략적인) 예상 완료 일정
_예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)_<br />
_(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)_
* 예상 완료 일정: 1주일 내

## 관련 이슈
_현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다._ <br />
_(특별한 일이 없다면 변경하지 않으셔도 됩니다.)_
* 관련 이슈: #483 (v1.12)

**Comment by 9bow** [comment]
안녕하세요, @kimtaehyeong 님.
제가 introyt 시리즈의 번역을 진행 중인데, 이런저런 이유로 진전이 더뎌 죄책감에 시달리던 중이었습니다 ^^;
* Issue: https://github.com/PyTorchKorea/tutorials-kr/issues/427
* PR: https://github.com/PyTorchKorea/tutorials-kr/pull/435
요 PR을 함께 진행해보시는 것은 어떠실련지요?

**Comment by kimtaehyeong** [comment]
>안녕하세요, @9bow 
번역 시리즈가 있는줄 몰랐네요, 혹시 제가 PR 보낸것 기반으로 작성하면 될까요 ? 아니면 참고해주신 시리즈 번역 기반으로 진행하면 될까요 ? 저도 뒷 부분도 계속 번역 중입니다.

**Comment by 9bow** [comment]
오랜 기간 진행이 없어 이슈를 닫습니다.
이후 진행하실 때 다시금 이슈를 열어주시거나 새로 만들어주시기를 부탁드립니다. :)
