### ISSUE TITLE
beginner_source/audio_feature_extractions_tutorial.py 번역

### ISSUE THREAD

**Issue by angus5552** [PyTorchKorea/tutorials-kr#624]
## 문서 URL
번역을 하실 / 요청하실 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/saving_loading_models.html)

URL: https://tutorials.pytorch.kr/beginner/audio_feature_augmentation_tutorial.html

## (대략적인) 예상 완료 일정
예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)

(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)

2월 20일

## 관련 이슈
현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다. 

(특별한 일이 없다면 수정하지 않으셔도 됩니다.)
https://github.com/PyTorchKorea/tutorials-kr/issues/615 (v1.13)

**Comment by 9bow** [comment]
v2.0에서 해당 튜토리얼이 삭제되어 본 이슈를 닫습니다.
(이후 torchaudio쪽 튜토리얼을 따로 정리 예정입니다.)
