### ISSUE TITLE
사용자 정의 데이터셋 문서 링크 클릭시 404 메시지 출력

### ISSUE THREAD

**Issue by corazzon** [PyTorchKorea/tutorials-kr#625]
## 이슈 내용
_어떤 이슈인지 알려주세요._
파이토치(PyTorch) 레시피 > 모든 레시피 보기 > 3페이지 > 
문서에서 [사용자 정의 데이터셋, Transforms & Dataloader](https://tutorials.pytorch.kr/recipes/recipes/custom_dataset_transforms_loader.html) 링크가 동작하지 않습니다.

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._
https://tutorials.pytorch.kr/recipes/recipes_index.html 의 3페이지 입니다.

**Comment by 9bow** [comment]
감사합니다 🙇🏽 
지난 commit들을 살펴보니, https://github.com/PyTorchKorea/tutorials-kr/commit/40300010d123e234e9e413ab0b18300518038b66 에서 해당 파일이 실수로 삭제된 것을 발견하였습니다.
바로 복구하도록 하겠습니다!

**Comment by 9bow** [comment]
https://tutorials.pytorch.kr/recipes/recipes/custom_dataset_transforms_loader.html
복구하였습니다. :)

현재 recepies index에 있는 제목과 문서 제목이 서로 다르게 나오고 있는데요, 혹시 이 내용을 추적(!)하셔서 별도 이슈와 PR 만들어주실 수 있으실까요? :)

**Comment by corazzon** [comment]
와! 빠른 복구 감사합니다 :)  recepies index 도 발견하면 이슈를 남기겠습니다!
