### ISSUE TITLE
`Intro_to_TorchScript_tutorial.html` 내 오탈자 수정 제안

### ISSUE THREAD

**Issue by sim-so** [PyTorchKorea/tutorials-kr#658]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**: https://tutorials.pytorch.kr/beginner/Intro_to_TorchScript_tutorial.html

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_
- '오토그라드가 작동하는 방식' 이미지 링크가 변경되어야 합니다.
[`Intro_to_TorchScript_tutorial.py`](https://github.com/PyTorchKorea/tutorials-kr/blob/master/beginner_source/Intro_to_TorchScript_tutorial.py#L157)의 157번째 줄입니다.
```
# .. figure:: https://github.com/pytorch/pytorch/raw/master/docs/source/_static/img/dynamic_graph.gif
```
(2)
- 위 링크에서 `master`를 `main`으로 바꾸어야 합니다. (저장소의 브랜치 이름이 변경되었습니다.)
```
# .. figure:: https://github.com/pytorch/pytorch/raw/main/docs/source/_static/img/dynamic_graph.gif
```

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._
- 영문버전 [튜토리얼](https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html#id1)과 [`Intro_to_TorchScript_tutorial.py`](https://github.com/pytorch/tutorials/blob/main/beginner_source/Intro_to_TorchScript_tutorial.py#L161) 문서를 참고했습니다.
- 저장소의 브랜치 이름이 변경되면서, 이미지를 포함하는 다른 문서에도 비슷한 문제가 있을 수 있겠습니다.

(추신 : 한국어 튜토리얼 제공에 항상 감사드립니다. 😊)

**Comment by 9bow** [comment]
감사합니다! PR도 만들어주실 수 있으실까요? :)

**Comment by sim-so** [comment]
@9bow님 확인 감사합니다!
이슈에 대한 PR을 만들었습니다(#659). 추가로 필요한 사항이 있다면 알려주세요!

**Comment by 9bow** [comment]
PR이 merge되어 이슈를 닫습니다 😃 
감사합니다!!
