### ISSUE TITLE
advanced/ddp_pipeline.py 오탈자 수정

### ISSUE THREAD

**Issue by sori9899** [PyTorchKorea/tutorials-kr#675]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**: https://tutorials.pytorch.kr/advanced/ddp_pipeline.html

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_

추가로, [분산 데이터 병렬 처리](https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html) 를 사용하여 이 파이프라인의 _두 복제를 훈련시킵니다_. 한 프로세스는 GPUs 0, 1에 거쳐 파이프를 구동하고 다른 프로세스는 GPUs 2, 3에서 파이프를 구동합니다. 그 다음, 이 두 프로세스는 분산 데이터 병렬처리로 두 복제본(replica)을 학습시킵니다.

(1) 이 파이프라인의 두 복제를 훈련시킵니다.

(2) 이 파이프라인의 두 복제본(replica)을 훈련시킵니다.

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

1) 위 문장에서 `두 복제를 훈련시킵니다`
    아래 문장에서 `두 복제본(replica)을 학습시킵니다` 라 적혀있어 문장의 통일성이 훼손되었기에 이를 변경해야 합니다.

**Comment by 9bow** [comment]
감사합니다. Pull Request 부탁드립니다. :+1:
