### ISSUE TITLE
introyt1_tutorial.py 단어 수정

### ISSUE THREAD

**Issue by robot703** [PyTorchKorea/tutorials-kr#677]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL : C:\Users\robot\OneDrive\문서\GitHub\ex-tutorials-kr\beginner_source\introyt**:

## 변경 사항
_(1)알고리짐은 잘 사용되지 않기 때문에 알고리즘으로 변경되는 것이 맞는 것 같습니다.

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

**Comment by 9bow** [comment]
감사합니다. Pull Request 부탁드립니다. :+1:
