### ISSUE TITLE
NGU

### ISSUE THREAD

**Issue by baochi0212** [PyTorchKorea/tutorials-kr#690]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**:

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._

**Comment by 9bow** [comment]
안녕하세요, @baochi0212 님. 이 이슈에 대해서 조금 더 설명해주실 수 있으실까요? 혹시 실수로 여신 것이라면 닫으려고 합니다. :)
Hi, @baochi0212 . I was wondering if you could shed some light on this issue, and if this is a mistake, I'd like to close it. :)
