### ISSUE TITLE
TRANSLATION_GUIDE.md 용어 제안

### ISSUE THREAD

**Issue by falconlee236** [PyTorchKorea/tutorials-kr#725]
## 이슈 내용
머신러닝을 공부하다보면 분류에 관련된 문제들이 많이 등장합니다. 특히 한 동물 사진을 주고 이 동물이 고양이인지 강아지인지 분류하는 이런 상황이 자주 등장합니다. 그럴때 머신러닝 분야에서는 __ground truth__ 라는 용어가 등장합니다. 그리고 이 단어는 등장할때 마다 한글로는 1대 1로 매칭되는 마땅한 단어가 없어서 항상 저에게는 골머리를 앓던 단어였습니다.  

저번주에 문서 오탈자 고정을 하면서 beginner/fgsm_tutorial.html 문서에 있는 ground truth label을 또 만나게 되었고 이번에는 확실히 정해보고자 해서 이슈 올립니다.  

위키피디아에서 ground truth는 원문으로 다음과 같이 소개하고 있습니다.  

> "Ground truth" may be seen as a conceptual term relative to the knowledge of the truth concerning a specific question. It is the ideal expected result.[[2]](https://en.wikipedia.org/wiki/Ground_truth#cite_note-2) This is used in [statistical models](https://en.wikipedia.org/wiki/Statistical_model) to prove or disprove [research](https://en.wikipedia.org/wiki/Research) [hypotheses](https://en.wikipedia.org/wiki/Hypothesis). The term "ground truthing" refers to the process of gathering the proper [objective](https://en.wikipedia.org/wiki/Objectivity_(philosophy)) (provable) data for this test. Compare with [gold standard](https://en.wikipedia.org/wiki/Gold_standard_(test)).    

간단히 제 나름대로 번역해보자면  Ground truth란 ...
* 특정한 질문에 대한 사실과 관련된 개념적 용어이다.
* 이상적인 예상 결과라고 불린다.
* 연구 가설을 증명하거나 반증하기 위해 사용하는 통계학적 모델에 사용된다.
* 연구할 때 우리가 목표로 하는 값을 모으는 과정이다.

이러한 자료를 바탕으로 저는 해당 용어를 
* 원본   
으로 번역하고 싶습니다.   

그렇게 생각한 이유는 위키피디아에서 설명하는 용어는 우리가 데이터를 분류할때 이 사진이 분류하고 싶은 대상이 있습니다. 예를들어 한 사진을 강아지라고 분류하고 싶습니다. 하지만 이 사진이 반드시 강아지라는 보장은 없습니다. 모델의 목표에 따라서 고양이에 더 비슷한 강아지이지만 이 사진을 강아지라고 분류하고 싶어하는 경우도 있을 수도 있습니다. 즉 이 용어는 실제 진실과는 다르지만 __해당 데이터의 원본__ 이라고 생각하기 때문에 다음과 같이 제안하게 되었습니다. 열렬한 피드백 환영입니다!!!!

## 추가 정보
[ground truth in Wikipedia](https://en.wikipedia.org/wiki/Ground_truth)

**Comment by kimgyujin** [comment]
ground-truth 자체는 명사로 쓰이는 게 아닌가요?
번역할 때도 명사형에 맞춰서 번역하는 게 더 맞지 않나라는 생각이 드네요.
