### ISSUE TITLE
quickstart_tutorial.py 코드 model.load_state_dict 함수에 weights_only=True 추가

### ISSUE THREAD

**Issue by rhkr8521** [PyTorchKorea/tutorials-kr#914]
## 문서 URL
_수정이 필요한 URL을 남겨주세요. (예. https://tutorials.pytorch.kr/beginner/basics/intro.html)_
- **URL**: https://tutorials.pytorch.kr/beginner/basics/quickstart_tutorial.html#id12

## 변경 사항
_(1)어떤 단어 / 문장 / 내용이 (2)어떻게 변경되어야 한다고 생각하세요?_
[pytorch/tutorials@afcd66](https://github.com/pytorch/tutorials/commit/afcd669d56554c2ef46f2da92edbfaf8c54043ec#diff-37dec87b5a67d7c394b5e5488291bf99f7e2298e6a60989ed77ba1c5384d6f16) 반영 Add weights_only=True to torch.load (#3012)

## 추가 정보
_위와 같이 생각하신 이유 또는 다른 참고할 정보가 있다면 알려주세요._
https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html#loading-models

**Comment by 9bow** [comment]
안녕하세요, @rhkr8521 님. 확인이 늦어서 PR까지 남기시고 나서 이슈를 확인했습니다. 죄송합니다.
남겨주신 PR들(#915, #934)에 덧글로 남겨드렸던 것처럼, 새로운 버전 반영은 누락되는 부분이 없도록 일괄적으로 진행하여 반영 예정입니다.
미리 관심 갖고 PR 남겨주셔서 감사합니다! :bow:
